### PR TITLE
Create Vault's Kubernetes Authentication and refactor Github/policies…

### PR DESCRIPTION
**Pull request by diego-ojeda-binbash**
… into separate layers

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a GitHub issue `#123`

### CODE REVIEW

**Review by exequielrafaela — COMMENTED** [review]
@diego-ojeda-binbash OJ If possible please let's have a README.md or inline comments with the commands we need to get the K8s root CA among some other things you've showed in yesterdays demo. Thanks in advance!

**Comment by diego-ojeda-binbash** [comment]
> @diego-ojeda-binbash OJ If possible please let's have a README.md or inline comments with the commands we need to get the K8s root CA among some other things you've showed in yesterdays demo. Thanks in advance!

@exequielrafaela Right. Will do. Thanks for the reminder!

**Comment by diego-ojeda-binbash** [comment]
@exequielrafaela Just for the record, the README with implementation steps and other instructions is here: https://github.com/binbashar/le-helm-infra/tree/master/apps-devstg/eks-vault

**Comment by exequielrafaela** [comment]
> @exequielrafaela Just for the record, the README with implementation steps and other instructions is here: https://github.com/binbashar/le-helm-infra/tree/master/apps-devstg/eks-vault

@diego-ojeda-binbash it looks great! Thanks for everything :)

**Pull request merged**
